title: Expressions
theme: minima
author: Ashish Singh Panwar
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ashish Singh Panwar's personal blog site.
  
# social links
twitter_username: AshishSPanwar # DO NOT include the @ character, or else the build will fail!
github_username:  ashishspanwar # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
